### PR TITLE
Obsidian Scythe & AOTE???

### PR DESCRIPTION
**Pull request by fortybyte**
AOTE ability added kind've
Added Obsidian Scythe *pls test and fix code prolly some typos*

### CODE REVIEW

**Comment by fortybyte** [comment]
actually don't accept and if you do accept can you fix the bugs and like sync it cause theres alot errors.

**Comment by ZenoCoding** [comment]
heheheheh nerd

**Review by fortybyte — COMMENTED** [review]
can you try this

**Review by ZenoCoding — APPROVED** [review]
very epic

**Pull request merged**
